# Generated by Django 5.2.3 on 2025-06-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_teachersubjectassignment_timetableslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstitutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_substitutions', to='timetable.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_logs', to='timetable.schoolprofile')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='timetable.teacher')),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_logs', to='timetable.timetableslot')),
            ],
            options={
                'verbose_name': 'Substitution Log',
                'verbose_name_plural': 'Substitution Logs',
                'ordering': ['-date', 'timetable_slot'],
            },
        ),
    ]
