# Generated by Django 5.0.6 on 2025-06-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_substitutionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_absences', to='timetable.schoolprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='timetable.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Absence',
                'verbose_name_plural': 'Teacher Absences',
                'ordering': ['-date', 'teacher'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
