# Generated by Django 5.0.6 on 2025-08-08 18:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_teacherabsence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='academic_year',
            field=models.CharField(blank=True, default='2024-2025', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='break_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='friday_closing_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='number_of_classes',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='period_duration_minutes',
            field=models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_code',
            field=models.CharField(default='SCH001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_end_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(default='My School', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='total_periods_per_day',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
